apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dapr
  namespace: flux-system
spec:
  interval: 1m
  url: https://dapr.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 1m
  releaseName: dapr
  chart:
    spec:
      chart: dapr
      version: '1.0.x'
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
      interval: 1m
  values:
    global.ha.enabled: false